# Generated by Django 5.2.2 on 2025-06-08 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='to_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='photos.photo'),
        ),
        migrations.AlterField(
            model_name='like',
            name='to_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='photos.photo'),
        ),
    ]
