# Generated by Django 5.2.2 on 2025-06-07 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(50)])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(50)])),
                ('profile_picture', models.URLField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Do not show', 'Do Not Show')], max_length=50)),
            ],
        ),
    ]
